### ISSUE TITLE
Feedback typo.

### ISSUE THREAD

**Issue by asukanan** [FlintyLemming/SurgeHandbook#4]
![97CDC92E-1846-453B-ABB8-683FCE4EA1D3](https://user-images.githubusercontent.com/54405882/120421827-9c9ed680-c399-11eb-86af-fe47bb8701ba.jpeg)

**Comment by FlintyLemming** [comment]
已修改
[关联 commit](https://github.com/FlintyLemming/SurgeHandbook/commit/7173c542edacf2a6783903d1114a7db4d1025453)
